import type { Metadata } from "next";
import "./globals.css";
//COMPONENTS
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import BackTop from "./Components/BackTop";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="flex flex-col justify-between">
        <Header />
        <main className="flex h-[100%] flex-col justify-center items-center w-full relative">
          {children}
          <BackTop />
        </main>
        <Footer />
      </body>
    </html>
  );
}
